In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print (torch.__version__)

1.13.1+cu116


## Introduction to Tensors
Tensors are numerical representation of data especially multi-dimensional 
representation.


#### Creating a tensor in python

torch.tensor creates tensor
https://pytorch.org/docs/stable/tensors.html

#### Scalar

In [4]:
# scalar- is a type of tensor

scalar = torch.tensor(7)

In [5]:
scalar   #tensor data type

tensor(7)

In [6]:
type(scalar)   #torch is module, and Tensor is a class within 

torch.Tensor

In [7]:
print(scalar)  

tensor(7)


In [8]:
scalar.ndim  #number of dimensions in the tensor

0

In [9]:
scalar.type

<function Tensor.type>

In [10]:
scalar.item()  #get the tensor as Python int

7

#### vector

In [11]:
# making a vector
vector = torch.tensor([2,3])

In [12]:
type(vector)

torch.Tensor

In [13]:
vector.shape

torch.Size([2])

In [14]:
vector.ndim  #number of pair of closing brakets

1

In [15]:
vector = torch.tensor([[2,3],[2,7]])

In [16]:
vector.ndim

2

In [17]:
vector.shape

torch.Size([2, 2])

In [18]:
vector3 = torch.tensor([[[5,6],
                         [8,9],
                         [90,76]]])

In [19]:
vector3.shape

torch.Size([1, 3, 2])

In [20]:
vector3.ndim

3

In [21]:
vector4 = torch.tensor([[[2,4,5],
                         [4,5,5],
                        [2,3,4]]])

In [22]:
vector4.ndim

3

In [23]:
vector4.shape

torch.Size([1, 3, 3])

#### making a matrix

In [24]:

MATRIX = torch.tensor([[2,3],[7,6]])

In [25]:
MATRIX.ndim

2

In [26]:
MATRIX.shape

torch.Size([2, 2])

In [27]:
MATRIX2 = torch.tensor([[1,2,3],[4,5,5],[2,3,9]])

In [28]:
MATRIX2.ndim

2

In [29]:
MATRIX2.shape

torch.Size([3, 3])

#### TENSOR

In [30]:
TENSOR = torch.tensor([[[2,3,3],
                        [2,7,6],
                       [3,6,8]]])

In [31]:
TENSOR.ndim

3

In [32]:
TENSOR.shape

torch.Size([1, 3, 3])

In [33]:
TENSOR =  torch.tensor([[[2,3,3],
                        [2,7,6],
                       [3,6,8]]])

In [34]:
TENSOR.ndim

3

In [35]:
TENSOR.shape # we hace 1, 3 by 1 tensor

torch.Size([1, 3, 3])

In [36]:
TENSOR[0]

tensor([[2, 3, 3],
        [2, 7, 6],
        [3, 6, 8]])

##Nomenclature

#### Lowercase - vectors, scalars

#### Upper case - TENSORS, MATRIX

#### Random tensors

Why Random tensors are important?  

Many neural network start with full of random numbers then adjust those random numbers to better represent the data


In [37]:
torch.rand(1)

tensor([0.5073])

In [38]:
a = torch.rand(2)

In [39]:
type(a)

torch.Tensor

In [40]:
torch.rand(1,2)

tensor([[0.1928, 0.0697]])

In [41]:
torch.rand(2,1,1)

tensor([[[0.4349]],

        [[0.5348]]])

In [42]:
torch.rand(2,2,2)

tensor([[[0.8274, 0.6262],
         [0.3969, 0.0615]],

        [[0.1061, 0.1447],
         [0.9067, 0.6961]]])

In [43]:
#1,1
torch.tensor([[1]]).shape

torch.Size([1, 1])

In [44]:
#1,2
torch.tensor([[2,2]]).shape

torch.Size([1, 2])

In [45]:
#1,3
torch.tensor([[2,3,4]]).shape

torch.Size([1, 3])

In [46]:
#1,1,3
torch.tensor([[[2,3,3]]]).shape

torch.Size([1, 1, 3])

In [47]:
#1,2,3
torch.tensor([[[1,2,2],
              [2,6,4]]]).shape

torch.Size([1, 2, 3])

In [48]:
#1,3,3
torch.tensor([[[2,3,4],
               [34,5,3],
               [434,5,3,]]]).shape

torch.Size([1, 3, 3])

In [49]:
#2,3,3 - start with the right most then start going left creating
torch.tensor([[[2,3,3],
             [3,3,3],
             [2,32,3]],
             
             [[2,3,4],
             [7,6,4],
             [3,79,9]]]).shape

torch.Size([2, 3, 3])

In [50]:
#2,3,4

#[3,4,5,5] #the right most number
#[[3,4,5,5],[4,34,53,3],[43,53,23,3]] #middle number is 3 so 3 of 4s
#[[[3,4,5,5],[4,34,53,3],[43,53,23,3]],[[3,4,5,5],[4,34,53,3],[43,53,23,3]]] #left most number is 2 so, copy of step 2 twice

torch.tensor([[[3,4,5,5],[4,34,53,3],[43,53,23,3]],[[3,4,5,5],[4,34,53,3],[43,53,23,3]]]).shape

torch.Size([2, 3, 4])

#### Image tensor
Height, width and colour channel (R, G, B)

All colours can be formed with red green and blue

In [51]:
random_image_size_tensor = torch.rand(3,224,224) # colour channel(Red,Green,Blue), height, width

In [52]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [53]:
random_tensor = torch.rand(3,2,2)

In [54]:
random_tensor

tensor([[[0.6493, 0.6216],
         [0.4515, 0.9084]],

        [[0.7442, 0.4610],
         [0.3721, 0.3890]],

        [[0.8405, 0.1150],
         [0.8039, 0.2501]]])

#### Zeroes and ones 

In [55]:
zeros = torch.zeros(3,2,2)

In [56]:
zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [57]:
#multiplying random_tensor(created above by zeros tensor)
#mask if we want to mask the number in a particular column of a tensor we can multiply that column by zero tensor to mask that column
zeros*random_tensor

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

#### ones

In [58]:
ones = torch.ones(3,4)

In [59]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Default data type is float32 for tensors

####  Creating range of tensors


In [60]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
random_tensor = torch.arange(10,100)
random_tensor

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Tensors like

#### this will copy a tensor size and fill it with zeros

In [63]:
random_tensor_like_zero = torch.zeros_like(random_tensor)

In [64]:
random_tensor_like_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor data type, and data type conversion


- float32 , 32 represents it stores 32 bit in memory.

- float16, 16 bits, it will take lesser memory
- The numbers represent precision, how much detail they will carry


#### Common errors people run into in py torch

1. Shape of tensors, shape not right
2. Tensors not on right device
3. Data type of tensors, wrong data type

In [65]:
tensor = torch.tensor([2,4,3])
                      

In [66]:
tensor.dtype

torch.int64

In [67]:
torch.tensor([2.0,2.0]).dtype

torch.float32

In [68]:
# converting data type of tensors

float_32_type = torch.tensor([2.0,3.0])

float_16 = float_32_type.type(torch.float16)

In [69]:
float_16

tensor([2., 3.], dtype=torch.float16)

In [70]:
float_32_type * float_16  # this works , 

tensor([4., 9.])

In [71]:
int_32_type = torch.tensor([1,23,2],
                           dtype=torch.int32)

In [72]:
long_type = torch.tensor([2,34,2,],
                         dtype=torch.long)

In [73]:
int_32_type*long_type

tensor([  2, 782,   4])

#### Information regarding tensors

In [74]:
tensor = torch.rand(2,3)
tensor

tensor([[0.2085, 0.4012, 0.4174],
        [0.4582, 0.6683, 0.0584]])

In [75]:
tensor.shape #to get the same

torch.Size([2, 3])

In [76]:
tensor.size() #this is function gives same result as tensor.shape attribute

torch.Size([2, 3])

In [77]:
tensor.device # the device the tensor is on

device(type='cpu')

#### Manipulating tensors

Tensor operations:

* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

#### Addition, subtraction and  multiplicaton


In [78]:
tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [79]:
tensor - 10

tensor([-9, -8, -7])

In [80]:
tensor *10 # element wise multiplication

tensor([10, 20, 30])

In [81]:
# torch in built fucntion

torch.mul(tensor,10)

tensor([10, 20, 30])

In [82]:
# torch in built addition

torch.add(tensor, 10)

tensor([11, 12, 13])

In [83]:
# torch in built substraction

torch.subtract(tensor, 10)

tensor([-9, -8, -7])

#### Matrix multiplication

* Elememt wise
* Dot product or matrix multiplication

In [84]:
# Element wise multiplication

tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])

In [85]:
tensor1 * tensor2

tensor([1, 4, 9])

In [86]:
# Matrix wise multiplication, 

# matmul function


torch.matmul(tensor1, tensor2)

tensor(14)

In [87]:
tensor1 = torch.tensor([2,3,6,3])
tensor2 = torch.tensor([2,3,8,4])

In [88]:
torch.matmul(tensor1,tensor2)

tensor(73)

In [89]:
tensor1 = torch.tensor([[2,3],[2,3]])
tensor2 = torch.tensor([[1,1],[1,1]])

In [90]:
torch.matmul(tensor1,tensor2)

tensor([[5, 5],
        [5, 5]])

#### Common errors while matrix multiplication:

1.**Inner dimensions** must match. 

(3,2)matmul(2,3)-this will work
(3,2)matlmul(3,2)- this will not work because inner dimensions i.e 2 and 3 do not match up.  

2.The resulting matrix has the shape of **outer dimensions**

matmul(torch.rand(3,10),torch.rand(10,3))- the output shape will be (3,3)


In [91]:
# torch.matmul(torch.rand(3,2),torch.rand(3,2)) #the inner dont match


In [92]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.8621, 0.8284, 1.0355],
        [1.1843, 1.0556, 1.3792],
        [0.9664, 1.0047, 1.2009]])

In [93]:
torch.rand(3,2)


tensor([[0.5852, 0.3821],
        [0.6771, 0.2660],
        [0.0563, 0.2582]])

#### Shape errors in tensors

1. To fix shape errors, we can manipulate the shape of one of our tensors using transpose.  
It switches the axes. for a shape of (2,3) it will make it of shape(3,2)

In [94]:
tensor_a = torch.tensor([[1,2],
                        [2,4],
                        [5,6]])

In [95]:
tensor_b = torch.tensor([[5,4],
                         [8,9],
                         [3,6]])

In [96]:
tensor_a.T.shape, tensor_b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [97]:
tensor_a.T

tensor([[1, 2, 5],
        [2, 4, 6]])

In [98]:
exx = torch.tensor([[1,2,4],
                    [3,9,6]])

In [99]:
exx.shape, exx.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

#### Tensor aggreagation (min, max, mean,sum etc)

In [100]:
tensor_a = torch.arange(0,100,10)
tensor_a

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [101]:
torch.min(tensor_a)

tensor(0)

In [102]:
torch.max(tensor_a)

tensor(90)

In [103]:
# torch.mean(tensor_a)   - this wont work because torch.mean dosent work with long datatype. the datatype is int64 or long
#https://pytorch.org/docs/stable/tensors.html

In [104]:
torch.mean(tensor_a.type(torch.float32))

tensor(45.)

In [105]:
tensor_a.sum()

tensor(450)

#### Finding position of value in tensor


In [106]:
x = torch.arange(1,100,10)

In [107]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [108]:
# finding
x.argmin()

tensor(0)

In [109]:
x.argmax()

tensor(9)

#### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping- reshapes an input to a defined shape

* View- return a view of an input tensor of certain shape but keeping the same memory as original tensor

* stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)

* squeeze - removes all '1' dimensions from a tensor

* unsqueeze - add a '1' dimension to a target tensor

* permute - return a view of the input tensor with dimensions permuted(swapped) in a certain way.



In [110]:
x = torch.arange(1,11)
x.shape,x,x.size()

(torch.Size([10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.Size([10]))

In [111]:
x_reshaped = x.reshape(1,10)

In [112]:
x_reshaped.shape,x_reshaped

(torch.Size([1, 10]), tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]))

In [113]:
 x_reshaped = x.reshape(2,10)  #cant double the number of elements

RuntimeError: ignored

In [ ]:
x_reshaped = x.reshape(1,11) #cant fit 11 tensor in the size of 10

In [ ]:
x_reshape = x.reshape(5,2)

x_reshape

In [ ]:
x_reshape = x.reshape(2,5)

x_reshape


##### changing the view

In [ ]:
x = torch.arange(1,11)
z = x.view(1,9)

In [ ]:
x = torch.arange(1,11)
z = x.view(1,10)

In [ ]:
x = torch.arange(1,11)
z = x.view(2,5)

#### Stack

In [ ]:
x = torch.rand(2,5)
x

In [ ]:
torch.stack([x,x])

In [ ]:
torch.stack([x,x],dim=2)

In [ ]:
torch.vstack([x,x])

In [ ]:
torch.hstack([x,x])

#### squeeze- removes 1d from tensor

In [ ]:
x = torch.rand(1,9)
x.shape, x

In [ ]:
x_new = x.squeeze()
x_new.shape,x_new  #one bracket less, it is converted to oone dimension

In [ ]:
x = torch.rand(10)
x.shape, x

In [ ]:
x_new = x.squeeze()
x_new.shape, x_new

In [ ]:
x = torch.rand(1,1,10)
x.shape, x



In [ ]:
x_new = x.squeeze()
x_new.shape, x_new   #all the one dimensions removed

In [ ]:
x = torch.rand(1,1,1,10)
x.shape, x


In [ ]:
x.squeeze(),x.squeeze().shape # all the three one-d removed

### Indexing
Selecting data from tesors

In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

In [ ]:
x[0]

In [ ]:
x[0][0]

In [ ]:
x[0][1]

In [ ]:
x[0][2]

In [ ]:
x[0][0][0]

In [ ]:
x[0][2][2]

In [ ]:
#we can use ":" to select "all" of a target dimension
x[:,0]  #all of zero dimension

In [ ]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x[:,:,1]

In [ ]:
# get all values of the 0 dimension but only 1 index value of1st and 2nd dimension
x[:, 1, 1]


In [ ]:
# get index 0 of 0th dimension and 1st dimension and all values of 2nd dimension

x[0,0,:]

In [ ]:
# index to get 9
x[0,2,2]

In [ ]:
#index to get 3,6,9
x[:,:,2]

#### Pytorch tensors and NumPY

* Data in NumPy, want in PyTorch --> 'torch.from_numpy(ndarray)'

* PyTorch tensor --> 'torch.Tensor.numpy()'

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

In [ ]:
array.dtype, tensor.dtype

In [ ]:
array = tensor.numpy()
array.dtype

#### Reproducibility -trying to take random out of random

Neural network start with random numbers- tensor operations- update random numbers to represent number data better- repeat  

To reduce the randomness in neural networks and pytorch , random seed is used.  


In [ ]:
a = torch.rand(3,2)
b = torch.rand(3,2)

print(a)
print(b)
print(a == b)

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)  #set every time

c = torch.rand(3,2)

torch.manual_seed(RANDOM_SEED)  #set every time
d = torch.rand(3,2)

print(c)
print(d)
print(c == d)

#https://pytorch.org/docs/stable/notes/randomness.html

#### Running tensors and PyTorch on GPUS

In [ ]:
torch.cuda.is_available()

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"