In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print (torch.__version__)

1.13.1+cu116


## Introduction to Tensors
Tensors are numerical representation of data especially multi-dimensional 
representation.


#### Creating a tensor in python

torch.tensor creates tensor
https://pytorch.org/docs/stable/tensors.html

#### Scalar

In [3]:
# scalar- is a type of tensor

scalar = torch.tensor(7)

In [4]:
scalar   #tensor data type

tensor(7)

In [5]:
type(scalar)   #torch is module, and Tensor is a class within 

torch.Tensor

In [6]:
print(scalar)  

tensor(7)


In [7]:
scalar.ndim  #number of dimensions in the tensor

0

In [8]:
scalar.type

<function Tensor.type>

In [9]:
scalar.item()  #get the tensor as Python int

7

#### vector

In [10]:
# making a vector
vector = torch.tensor([2,3])

In [11]:
type(vector)

torch.Tensor

In [12]:
vector.shape

torch.Size([2])

In [13]:
vector.ndim  #number of pair of closing brakets

1

In [14]:
vector = torch.tensor([[2,3],[2,7]])

In [15]:
vector.ndim

2

In [16]:
vector.shape

torch.Size([2, 2])

In [17]:
vector3 = torch.tensor([[[5,6],
                         [8,9],
                         [90,76]]])

In [18]:
vector3.shape

torch.Size([1, 3, 2])

In [19]:
vector3.ndim

3

In [20]:
vector4 = torch.tensor([[[2,4,5],
                         [4,5,5],
                        [2,3,4]]])

In [21]:
vector4.ndim

3

In [22]:
vector4.shape

torch.Size([1, 3, 3])

#### making a matrix

In [23]:

MATRIX = torch.tensor([[2,3],[7,6]])

In [24]:
MATRIX.ndim

2

In [25]:
MATRIX.shape

torch.Size([2, 2])

In [26]:
MATRIX2 = torch.tensor([[1,2,3],[4,5,5],[2,3,9]])

In [27]:
MATRIX2.ndim

2

In [28]:
MATRIX2.shape

torch.Size([3, 3])

#### TENSOR

In [29]:
TENSOR = torch.tensor([[[2,3,3],
                        [2,7,6],
                       [3,6,8]]])

In [30]:
TENSOR.ndim

3

In [31]:
TENSOR.shape

torch.Size([1, 3, 3])

In [32]:
TENSOR =  torch.tensor([[[2,3,3],
                        [2,7,6],
                       [3,6,8]]])

In [33]:
TENSOR.ndim

3

In [34]:
TENSOR.shape # we hace 1, 3 by 1 tensor

torch.Size([1, 3, 3])

In [35]:
TENSOR[0]

tensor([[2, 3, 3],
        [2, 7, 6],
        [3, 6, 8]])

##Nomenclature

#### Lowercase - vectors, scalars

#### Upper case - TENSORS, MATRIX

#### Random tensors

Why Random tensors are important?  

Many neural network start with full of random numbers then adjust those random numbers to better represent the data


In [36]:
torch.rand(1)

tensor([0.2219])

In [37]:
a = torch.rand(2)

In [38]:
type(a)

torch.Tensor

In [39]:
torch.rand(1,2)

tensor([[0.4426, 0.7946]])

In [40]:
torch.rand(2,1,1)

tensor([[[0.5842]],

        [[0.9787]]])

In [41]:
torch.rand(2,2,2)

tensor([[[0.0356, 0.3984],
         [0.8836, 0.5310]],

        [[0.0514, 0.3291],
         [0.1762, 0.1293]]])

In [42]:
#1,1
torch.tensor([[1]]).shape

torch.Size([1, 1])

In [43]:
#1,2
torch.tensor([[2,2]]).shape

torch.Size([1, 2])

In [44]:
#1,3
torch.tensor([[2,3,4]]).shape

torch.Size([1, 3])

In [45]:
#1,1,3
torch.tensor([[[2,3,3]]]).shape

torch.Size([1, 1, 3])

In [46]:
#1,2,3
torch.tensor([[[1,2,2],
              [2,6,4]]]).shape

torch.Size([1, 2, 3])

In [47]:
#1,3,3
torch.tensor([[[2,3,4],
               [34,5,3],
               [434,5,3,]]]).shape

torch.Size([1, 3, 3])

In [48]:
#2,3,3 - start with the right most then start going left creating
torch.tensor([[[2,3,3],
             [3,3,3],
             [2,32,3]],
             
             [[2,3,4],
             [7,6,4],
             [3,79,9]]]).shape

torch.Size([2, 3, 3])

In [49]:
#2,3,4

#[3,4,5,5] #the right most number
#[[3,4,5,5],[4,34,53,3],[43,53,23,3]] #middle number is 3 so 3 of 4s
#[[[3,4,5,5],[4,34,53,3],[43,53,23,3]],[[3,4,5,5],[4,34,53,3],[43,53,23,3]]] #left most number is 2 so, copy of step 2 twice

torch.tensor([[[3,4,5,5],[4,34,53,3],[43,53,23,3]],[[3,4,5,5],[4,34,53,3],[43,53,23,3]]]).shape

torch.Size([2, 3, 4])

#### Image tensor
Height, width and colour channel (R, G, B)

All colours can be formed with red green and blue

In [50]:
random_image_size_tensor = torch.rand(3,224,224) # colour channel(Red,Green,Blue), height, width

In [51]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [52]:
random_tensor = torch.rand(3,2,2)

In [53]:
random_tensor

tensor([[[0.6330, 0.7814],
         [0.1033, 0.8564]],

        [[0.6215, 0.7150],
         [0.6840, 0.4497]],

        [[0.6547, 0.8327],
         [0.4866, 0.0647]]])

#### Zeroes and ones 

In [54]:
zeros = torch.zeros(3,2,2)

In [55]:
zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [56]:
#multiplying random_tensor(created above by zeros tensor)
#mask if we want to mask the number in a particular column of a tensor we can multiply that column by zero tensor to mask that column
zeros*random_tensor

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

#### ones

In [57]:
ones = torch.ones(3,4)

In [58]:
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#### Default data type is float32 for tensors

####  Creating range of tensors


In [59]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
random_tensor = torch.arange(10,100)
random_tensor

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#### Tensors like

#### this will copy a tensor size and fill it with zeros

In [62]:
random_tensor_like_zero = torch.zeros_like(random_tensor)

In [63]:
random_tensor_like_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor data type, and data type conversion


- float32 , 32 represents it stores 32 bit in memory.

- float16, 16 bits, it will take lesser memory
- The numbers represent precision, how much detail they will carry


#### Common errors people run into in py torch

1. Shape of tensors, shape not right
2. Tensors not on right device
3. Data type of tensors, wrong data type

In [64]:
tensor = torch.tensor([2,4,3])
                      

In [65]:
tensor.dtype

torch.int64

In [66]:
torch.tensor([2.0,2.0]).dtype

torch.float32

In [67]:
# converting data type of tensors

float_32_type = torch.tensor([2.0,3.0])

float_16 = float_32_type.type(torch.float16)

In [68]:
float_16

tensor([2., 3.], dtype=torch.float16)

In [69]:
float_32_type * float_16  # this works , 

tensor([4., 9.])

In [70]:
int_32_type = torch.tensor([1,23,2],
                           dtype=torch.int32)

In [71]:
long_type = torch.tensor([2,34,2,],
                         dtype=torch.long)

In [72]:
int_32_type*long_type

tensor([  2, 782,   4])

#### Information regarding tensors

In [73]:
tensor = torch.rand(2,3)
tensor

tensor([[0.2235, 0.3830, 0.6691],
        [0.3640, 0.3311, 0.5571]])

In [74]:
tensor.shape #to get the same

torch.Size([2, 3])

In [75]:
tensor.size() #this is function gives same result as tensor.shape attribute

torch.Size([2, 3])

In [76]:
tensor.device # the device the tensor is on

device(type='cpu')

#### Manipulating tensors

Tensor operations:

* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

#### Addition, subtraction and  multiplicaton


In [77]:
tensor = torch.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [78]:
tensor - 10

tensor([-9, -8, -7])

In [79]:
tensor *10 # element wise multiplication

tensor([10, 20, 30])

In [80]:
# torch in built fucntion

torch.mul(tensor,10)

tensor([10, 20, 30])

In [81]:
# torch in built addition

torch.add(tensor, 10)

tensor([11, 12, 13])

In [82]:
# torch in built substraction

torch.subtract(tensor, 10)

tensor([-9, -8, -7])

#### Matrix multiplication

* Elememt wise
* Dot product or matrix multiplication

In [83]:
# Element wise multiplication

tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([1,2,3])

In [84]:
tensor1 * tensor2

tensor([1, 4, 9])

In [85]:
# Matrix wise multiplication, 

# matmul function


torch.matmul(tensor1, tensor2)

tensor(14)

In [86]:
tensor1 = torch.tensor([2,3,6,3])
tensor2 = torch.tensor([2,3,8,4])

In [87]:
torch.matmul(tensor1,tensor2)

tensor(73)

In [88]:
tensor1 = torch.tensor([[2,3],[2,3]])
tensor2 = torch.tensor([[1,1],[1,1]])

In [89]:
torch.matmul(tensor1,tensor2)

tensor([[5, 5],
        [5, 5]])

#### Common errors while matrix multiplication:

1.**Inner dimensions** must match. 

(3,2)matmul(2,3)-this will work
(3,2)matlmul(3,2)- this will not work because inner dimensions i.e 2 and 3 do not match up.  

2.The resulting matrix has the shape of **outer dimensions**

matmul(torch.rand(3,10),torch.rand(10,3))- the output shape will be (3,3)


In [90]:
# torch.matmul(torch.rand(3,2),torch.rand(3,2)) #the inner dont match


In [91]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.7521, 0.7526, 0.7166],
        [0.6649, 0.6167, 0.1551],
        [0.8265, 0.7908, 0.4315]])

In [92]:
torch.rand(3,2)


tensor([[0.6003, 0.1770],
        [0.6291, 0.7307],
        [0.1948, 0.1928]])

#### Shape errors in tensors

1. To fix shape errors, we can manipulate the shape of one of our tensors using transpose.  
It switches the axes. for a shape of (2,3) it will make it of shape(3,2)

In [93]:
tensor_a = torch.tensor([[1,2],
                        [2,4],
                        [5,6]])

In [94]:
tensor_b = torch.tensor([[5,4],
                         [8,9],
                         [3,6]])

In [95]:
tensor_a.T.shape, tensor_b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [96]:
tensor_a.T

tensor([[1, 2, 5],
        [2, 4, 6]])

In [97]:
exx = torch.tensor([[1,2,4],
                    [3,9,6]])

In [98]:
exx.shape, exx.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

#### Tensor aggreagation (min, max, mean,sum etc)

In [99]:
tensor_a = torch.arange(0,100,10)
tensor_a

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [100]:
torch.min(tensor_a)

tensor(0)

In [101]:
torch.max(tensor_a)

tensor(90)

In [102]:
# torch.mean(tensor_a)   - this wont work because torch.mean dosent work with long datatype. the datatype is int64 or long
#https://pytorch.org/docs/stable/tensors.html

In [103]:
torch.mean(tensor_a.type(torch.float32))

tensor(45.)

In [104]:
tensor_a.sum()

tensor(450)

#### Finding position of value in tensor


In [112]:
x = torch.arange(1,100,10)

In [113]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [114]:
# finding
x.argmin()

tensor(0)

In [115]:
x.argmax()

tensor(9)

#### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping- reshapes an input to a defined shape

* View- return a view of an input tensor of certain shape but keeping the same memory as original tensor

* stacking - combine multiple tensors on top of each other(vstack) or side by side(hstack)

* squeeze - removes all '1' dimensions from a tensor

* unsqueeze - add a '1' dimension to a target tensor

* permute - return a view of the input tensor with dimensions permuted(swapped) in a certain way.



In [141]:
x = torch.arange(1,11)
x.shape,x,x.size()

(torch.Size([10]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 torch.Size([10]))

In [143]:
x_reshaped = x.reshape(1,10)

In [144]:
x_reshaped.shape,x_reshaped

(torch.Size([1, 10]), tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]))

In [145]:
 x_reshaped = x.reshape(2,10)  #cant double the number of elements

RuntimeError: ignored

In [147]:
x_reshaped = x.reshape(1,11) #cant fit 11 tensor in the size of 10

RuntimeError: ignored

In [152]:
x_reshape = x.reshape(5,2)

x_reshape

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [154]:
x_reshape = x.reshape(2,5)

x_reshape


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

##### changing the view

In [158]:
x = torch.arange(1,11)
z = x.view(1,9)

RuntimeError: ignored

In [159]:
x = torch.arange(1,11)
z = x.view(1,10)

In [160]:
x = torch.arange(1,11)
z = x.view(2,5)

#### Stack

In [163]:
x = torch.rand(2,5)
x

tensor([[0.9972, 0.4023, 0.0754, 0.6157, 0.8910],
        [0.5773, 0.9861, 0.7720, 0.2355, 0.6781]])

In [168]:
torch.stack([x,x])

tensor([[[0.9972, 0.4023, 0.0754, 0.6157, 0.8910],
         [0.5773, 0.9861, 0.7720, 0.2355, 0.6781]],

        [[0.9972, 0.4023, 0.0754, 0.6157, 0.8910],
         [0.5773, 0.9861, 0.7720, 0.2355, 0.6781]]])

In [171]:
torch.stack([x,x],dim=2)

tensor([[[0.9972, 0.9972],
         [0.4023, 0.4023],
         [0.0754, 0.0754],
         [0.6157, 0.6157],
         [0.8910, 0.8910]],

        [[0.5773, 0.5773],
         [0.9861, 0.9861],
         [0.7720, 0.7720],
         [0.2355, 0.2355],
         [0.6781, 0.6781]]])

In [175]:
torch.vstack([x,x])

tensor([[0.9972, 0.4023, 0.0754, 0.6157, 0.8910],
        [0.5773, 0.9861, 0.7720, 0.2355, 0.6781],
        [0.9972, 0.4023, 0.0754, 0.6157, 0.8910],
        [0.5773, 0.9861, 0.7720, 0.2355, 0.6781]])

In [176]:
torch.hstack([x,x])

tensor([[0.9972, 0.4023, 0.0754, 0.6157, 0.8910, 0.9972, 0.4023, 0.0754, 0.6157,
         0.8910],
        [0.5773, 0.9861, 0.7720, 0.2355, 0.6781, 0.5773, 0.9861, 0.7720, 0.2355,
         0.6781]])

#### squeeze- removes 1d from tensor

In [179]:
x = torch.rand(1,9)
x.shape, x

(torch.Size([1, 9]),
 tensor([[0.5581, 0.6975, 0.7756, 0.9009, 0.6548, 0.1206, 0.0942, 0.7007, 0.5508]]))

In [182]:
x_new = x.squeeze()
x_new.shape,x_new  #one bracket less, it is converted to oone dimension

(torch.Size([9]),
 tensor([0.5581, 0.6975, 0.7756, 0.9009, 0.6548, 0.1206, 0.0942, 0.7007, 0.5508]))

In [184]:
x = torch.rand(10)
x.shape, x

(torch.Size([10]),
 tensor([0.0586, 0.6386, 0.9243, 0.5415, 0.4367, 0.9822, 0.3184, 0.5852, 0.6336,
         0.2728]))

In [185]:
x_new = x.squeeze()
x_new.shape, x_new

(torch.Size([10]),
 tensor([0.0586, 0.6386, 0.9243, 0.5415, 0.4367, 0.9822, 0.3184, 0.5852, 0.6336,
         0.2728]))

In [200]:
x = torch.rand(1,1,10)
x.shape, x



(torch.Size([10]),
 tensor([0.8276, 0.9920, 0.5658, 0.2884, 0.5049, 0.8780, 0.1984, 0.1959, 0.1918,
         0.2693]))

In [201]:
x_new = x.squeeze()
x_new.shape, x_new   #all the one dimensions removed

(torch.Size([10]),
 tensor([0.8276, 0.9920, 0.5658, 0.2884, 0.5049, 0.8780, 0.1984, 0.1959, 0.1918,
         0.2693]))

In [202]:
x = torch.rand(1,1,1,10)
x.shape, x


(torch.Size([1, 1, 1, 10]),
 tensor([[[[0.5619, 0.2034, 0.1940, 0.2342, 0.4920, 0.9721, 0.7750, 0.6146,
            0.1224, 0.6345]]]]))

In [205]:
x.squeeze(),x.squeeze().shape # all the three one-d removed

(tensor([0.5619, 0.2034, 0.1940, 0.2342, 0.4920, 0.9721, 0.7750, 0.6146, 0.1224,
         0.6345]), torch.Size([10]))

### Indexing
Selecting data from tesors

In [207]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [208]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [210]:
x[0][0]

tensor([1, 2, 3])

In [212]:
x[0][1]

tensor([4, 5, 6])

In [213]:
x[0][2]

tensor([7, 8, 9])

In [214]:
x[0][0][0]

tensor(1)

In [216]:
x[0][2][2]

tensor(9)

In [217]:
#we can use ":" to select "all" of a target dimension
x[:,0]  #all of zero dimension

tensor([[1, 2, 3]])

In [218]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

x[:,:,1]

tensor([[2, 5, 8]])

In [219]:
# get all values of the 0 dimension but only 1 index value of1st and 2nd dimension
x[:, 1, 1]


tensor([5])

In [220]:
# get index 0 of 0th dimension and 1st dimension and all values of 2nd dimension

x[0,0,:]

tensor([1, 2, 3])

In [221]:
# index to get 9
x[0,2,2]

tensor(9)

In [222]:
#index to get 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

#### Pytorch tensors and NumPY

* Data in NumPy, want in PyTorch --> 'torch.from_numpy(ndarray)'

* PyTorch tensor --> 'torch.Tensor.numpy()'

In [223]:
import torch
import numpy as np

In [231]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [232]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float64)

In [234]:
array = tensor.numpy()
array.dtype

dtype('float64')

#### Reproducibility -trying to take random out of random

Neural network start with random numbers- tensor operations- update random numbers to represent number data better- repeat  

To reduce the randomness in neural networks and pytorch , random seed is used.  


In [236]:
a = torch.rand(3,2)
b = torch.rand(3,2)

print(a)
print(b)
print(a == b)

tensor([[0.1881, 0.7941],
        [0.0631, 0.6999],
        [0.1547, 0.2941]])
tensor([[0.2621, 0.1531],
        [0.4200, 0.7909],
        [0.0867, 0.8036]])
tensor([[False, False],
        [False, False],
        [False, False]])


In [239]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)  #set every time

c = torch.rand(3,2)

torch.manual_seed(RANDOM_SEED)  #set every time
d = torch.rand(3,2)

print(c)
print(d)
print(c == d)

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])
tensor([[0.8823, 0.9150],
        [0.3829, 0.9593],
        [0.3904, 0.6009]])
tensor([[True, True],
        [True, True],
        [True, True]])


#https://pytorch.org/docs/stable/notes/randomness.html

#### Running tensors and PyTorch on GPUS

In [240]:
torch.cuda.is_available()

False

In [241]:
device = "cuda" if torch.cuda.is_available() else "cpu"